# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: unicode
  database: picture-feed-db
  pool: 5
  username:
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: picture-feed-db
  pool: 5
  username:
  password:
  timeout: 5000
